version: "3.8"

services:
  db:
    image: postgres
    restart: unless-stopped  # Add this line to specify the restart policy
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    restart: unless-stopped  # Add this line to specify the restart policy
    ports:
      - "6379:6379"

  web:
    depends_on:
      - db
      - redis
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      RAILS_ENV: development
      RAILS_MAX_THREADS: 5
      REDIS_HOST: redis
      REDIS_PORT: 6379
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    restart: unless-stopped  # Add this line to specify the restart policy

  # sidekiq:
  #   build: .
  #   command: bundle exec sidekiq
  #   volumes:
  #     - .:/app
  #   environment:
  #     RAILS_ENV: development
  #     REDIS_HOST: redis
  #     REDIS_PORT: 6379
  #     POSTGRES_USER: ${POSTGRES_USER}
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  #     POSTGRES_HOST: ${POSTGRES_HOST}
  #   depends_on:
  #     - redis
  #   restart: unless-stopped  # Add this line to specify the restart policy

volumes:
  redis:
  db-data:
